# Generated by Django 5.1.1 on 2024-09-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_video_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='d', max_length=50, null=True)),
                ('password', models.CharField(default='d', max_length=8, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='male',
            name='girl',
        ),
        migrations.RemoveField(
            model_name='user',
            name='products',
        ),
        migrations.RemoveField(
            model_name='username',
            name='watch',
        ),
        migrations.DeleteModel(
            name='Female',
        ),
        migrations.DeleteModel(
            name='Male',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserName',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
